In [1]:
import numpy as np

In [17]:
M = np.arange(6).reshape(2, 3)

In [18]:
M

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
np.sqrt(M)

array([[ 0.        ,  1.        ,  1.41421356],
       [ 1.73205081,  2.        ,  2.23606798]])

In [20]:
np.exp(M)

array([[   1.        ,    2.71828183,    7.3890561 ],
       [  20.08553692,   54.59815003,  148.4131591 ]])

In [28]:
np.max(M, axis=0)

array([3, 4, 5])

In [29]:
np.max(M, axis=1)

array([2, 5])