In [1]:
import numpy as np

In [3]:
M = np.arange(100).reshape(10, 10)

In [9]:
M

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
M[2,3]

23

In [6]:
M[2, :]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
M[:, 2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [8]:
M[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [13]:
M[3:7, 1:5]

array([[31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64]])

In [12]:
M[:5, :5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [14]:
M[[1,3,5], [2,4,6]]

array([12, 34, 56])

In [15]:
M[::2, ::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [16]:
M[::-2, ::-2]

array([[99, 97, 95, 93, 91],
       [79, 77, 75, 73, 71],
       [59, 57, 55, 53, 51],
       [39, 37, 35, 33, 31],
       [19, 17, 15, 13, 11]])

In [20]:
M[M > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])